version: '3.8'

services:
  web:
    build: .
    container_name: diary
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code  
    ports:
      - "8000:8000"  
    env_file:
      - .my_diary/.env  
    depends_on:
      - db
      - redis  
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - .env  
    volumes:
      - db_data:/var/lib/postgresql/data 
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: unless-stopped

volumes:
  db_data:
    driver: local

